set encoding=utf-8
" theme
colorscheme monokai

" Don't try to be vi compatible
set nocompatible

" syntax highlighting
syntax on

" search hightlight
set hlsearch

" show file name always in status line
set laststatus=2

" line numbers
set number relativenumber
set numberwidth=5

" sensible
set backspace=2
set nobackup
set nowritebackup
set noswapfile
set splitbelow
set splitright

" ruler
set ruler
set textwidth=80
set colorcolumn=+1

" indenting
set autoindent
set smartindent

" whitespace
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" spelling
set spelllang=en_gb
set complete+=kspell

" spelling for filetypes
autocmd FileType gitcommit setlocal spell
autocmd BufRead,BufNewFile *.md setlocal spell

" netrw
let g:netrw_liststyle = 3
let g:netrw_banner = 0

" leader is space
let mapleader = " "

" don't use arrow keys
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" RSpec.vim
let g:rspec_command = "!bundle exec rspec --drb {spec}"

map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

" ALE
let g:ale_lint_on_save =  0
let g:ale_lint_on_insert_leave = 1
let g:ale_linters_explicit = 1
let g:ale_sign_column_always = 1
let g:ale_lint_on_text_changed = 'always'

let g:ale_linters = {
\   'ruby': ['standardrb','solargraph'],
\}

let g:ale_fix_on_save = 1

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\}

" go to definition, requires solargraph
:map <leader>d :ALEGoToDefinition<CR>
