set encoding=utf-8
" theme
colorscheme monokai

" Don't try to be vi compatible
set nocompatible

" syntax highlighting
syntax on

" line numbers
set number relativenumber
set numberwidth=5

" sensible
set backspace=2
set nobackup
set nowritebackup
set noswapfile

" ruler
set ruler
set textwidth=80
set colorcolumn=+1

" indenting
set autoindent
set smartindent

" whitespace
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" spelling
set spelllang=en_gb
set complete+=kspell

" spelling for filetypes
autocmd FileType gitcommit setlocal spell
autocmd BufRead,BufNewFile *.md setlocal spell

" netrw
let g:netrw_liststyle = 3
let g:netrw_banner = 0

" don't use arrow keys
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" RSpec.vim
let g:rspec_command = "!bundle exec rspec --drb {spec}"

" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
