" Don't try to be vi compatible
set nocompatible

" syntax highlighting
syntax on

" line numbers
set number

" ruler
set ruler

" whitespace
set wrap
set textwidth=79
set tabstop=2
set softtabstop=2

" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
