# add all the sub files
source ~/.zsh/options.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/utilities.zsh
source ~/.zsh/history.zsh
source ~/.zsh/async.zsh
source ~/.zsh/pure.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# turn on git stash status
zstyle :prompt:pure:git:stash show yes

# prompt
PROMPT=" $PROMPT"

# chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh

# node 10
export PATH="/usr/local/opt/node@10/bin:$PATH"
