# add pure to the laod path
fpath+=$HOME/src/pure

# add all the local bits
source ~/src/dotfiles/zsh/options.zsh
source ~/src/dotfiles/zsh/exports.zsh
source ~/src/dotfiles/zsh/completion.zsh
source ~/src/dotfiles/zsh/aliases.zsh
source ~/src/dotfiles/zsh/bindkeys.zsh
source ~/src/dotfiles/zsh/utilities.zsh
source ~/src/dotfiles/zsh/history.zsh

# Intel Homebrew
# eval "$(/usr/local/bin/brew shellenv)"

# Apple Silicon Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# direnv
eval "$(direnv hook zsh)"

# syntax highlighting
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# chruby
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh

# chnode
source $HOMEBREW_PREFIX/opt/chnode/share/chnode/chnode.sh
source $HOMEBREW_PREFIX/opt/chnode/share/chnode/auto.sh

# turn on git stash status
zstyle :prompt:pure:git:stash show yes

# initalise pure prompt
autoload -U promptinit; promptinit
prompt pure

# auto load node version
precmd_functions+=(chnode_auto)
